Update CI scheduled jobs
ponylang/contributors pull request #15
Opened 2021-01-22 23:50 UTC by SeanTAllen

Most scheduled jobs have been switched to being triggered by events that
happen in other repos.

2021-01-23 19:25 UTC, EpicEric requested changes

2021-01-23 19:25 UTC, EpicEric commented on ci/triggered-jobs.md
> +- [ponyup: breakage-against-linux-ponyc-latest](https://github.com/ponyup/appdirs/blob/master/.github/workflows/breakage-against-ponyc-latest.yml)
```suggestion
- [ponyup: breakage-against-linux-ponyc-latest](https://github.com/ponylang/ponyup/blob/master/.github/workflows/breakage-against-ponyc-latest.yml)
```

2021-01-23 19:25 UTC, EpicEric commented on ci/triggered-jobs.md
> +- [shared-docker: linux-builder-update]()
This link is broken.

2021-01-23 21:24 UTC, SeanTAllen commented on ci/triggered-jobs.md
> +- [shared-docker: linux-builder-update]()
Fixed.

2021-01-23 21:25 UTC, SeanTAllen commented
@EpicEric can you give this another review? if it's good, can you squash and merge?

2021-01-24 01:48 UTC, EpicEric approved these changes

2021-01-24 01:48 UTC, merged